/**
 * Semantic icon roles, ported from the nuxtseo design system registry and
 * resolved to Octicons, the one icon set this dashboard uses. A role that is
 * not listed passes through unchanged, so an explicit `i-octicon-*` id works.
 */
export const uiIconRoles = {
  next: 'i-octicon-arrow-right-16',
  back: 'i-octicon-arrow-left-16',
  up: 'i-octicon-arrow-up-16',
  down: 'i-octicon-arrow-down-16',
  external: 'i-octicon-link-external-16',
  expand: 'i-octicon-chevron-down-16',
  collapse: 'i-octicon-chevron-up-16',
  'chevron-down': 'i-octicon-chevron-down-16',
  'chevron-up': 'i-octicon-chevron-up-16',
  'chevron-right': 'i-octicon-chevron-right-16',
  'chevron-left': 'i-octicon-chevron-left-16',
  'arrow-up-right': 'i-octicon-arrow-up-right-16',
  'arrow-down-right': 'i-octicon-arrow-down-right-16',
  sort: 'i-octicon-arrow-switch-16',
  add: 'i-octicon-plus-16',
  close: 'i-octicon-x-16',
  x: 'i-octicon-x-16',
  delete: 'i-octicon-trash-16',
  edit: 'i-octicon-pencil-16',
  copy: 'i-octicon-copy-16',
  check: 'i-octicon-check-16',
  refresh: 'i-octicon-sync-16',
  search: 'i-octicon-search-16',
  download: 'i-octicon-download-16',
  upload: 'i-octicon-upload-16',
  filter: 'i-octicon-filter-16',
  settings: 'i-octicon-gear-16',
  more: 'i-octicon-kebab-horizontal-16',
  'more-horizontal': 'i-octicon-kebab-horizontal-16',
  minus: 'i-octicon-dash-16',
  stop: 'i-octicon-stop-16',
  play: 'i-octicon-play-16',
  info: 'i-octicon-info-16',
  note: 'i-octicon-info-16',
  help: 'i-octicon-question-16',
  tip: 'i-octicon-light-bulb-16',
  warning: 'i-octicon-alert-16',
  alert: 'i-octicon-alert-16',
  caution: 'i-octicon-alert-16',
  success: 'i-octicon-check-circle-16',
  error: 'i-octicon-x-circle-16',
  lock: 'i-octicon-lock-16',
  view: 'i-octicon-eye-16',
  hide: 'i-octicon-eye-closed-16',
  bot: 'i-octicon-hubot-16',
  star: 'i-octicon-star-16',
  bell: 'i-octicon-bell-16',
  shield: 'i-octicon-shield-16',
  zap: 'i-octicon-zap-16',
  tag: 'i-octicon-tag-16',
  pin: 'i-octicon-pin-16',
  bug: 'i-octicon-bug-16',
  loading: 'i-octicon-sync-16',
  light: 'i-octicon-sun-16',
  dark: 'i-octicon-moon-16',
  system: 'i-octicon-device-desktop-16',
  calendar: 'i-octicon-calendar-16',
  clock: 'i-octicon-clock-16',
  chart: 'i-octicon-graph-16',
  empty: 'i-octicon-inbox-16',
  home: 'i-octicon-home-16',
  link: 'i-octicon-link-16',
  file: 'i-octicon-file-16',
  folder: 'i-octicon-file-directory-16',
  globe: 'i-octicon-globe-16',
  repo: 'i-octicon-repo-16',
  issue: 'i-octicon-issue-opened-16',
  'pull-request': 'i-octicon-git-pull-request-16',
  commit: 'i-octicon-git-commit-16',
} as const

export type UiIconRole = keyof typeof uiIconRoles
/** A semantic role, or any explicit `i-*` icon id. */
export type UiIcon = UiIconRole | (string & {})

export function resolveUiIcon(name: string): string {
  return name in uiIconRoles ? uiIconRoles[name as UiIconRole] : name
}
